services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=moose
      - POSTGRES_PASSWORD=moose
      - POSTGRES_DB=moose_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  migrate:
    image: migrate/migrate
    profiles:
      - tools
    volumes:
      - ./packages/db/migrations:/migrations
    networks:
      - app-network
    command:
      - -path=/migrations/
      - -database=postgres://moose:moose@db:5432/moose_db?sslmode=disable
      - up
  api:
    build:
      context: ./packages/api
    ports:
      - "8080:8080"
    volumes:
      - ./packages/api:/app/packages/api
      - ./packages/db:/app/packages/db
      - /app/packages/api/tmp # Anonymous volume for hot-reload tmp files
      - pkg_cache:/go/pkg 
   
    working_dir: /app/packages/api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=moose
      - DB_PASSWORD=moose
      - DB_NAME=moose_db
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./packages/www
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./packages/www:/app:Z
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api
    networks:
      - app-network

  storybook:
    build:
      context: ./packages/www
    working_dir: /app
    ports:
      - "6006:6006"
    volumes:
      - ./packages/www:/app:Z
      - /app/node_modules
    networks:
      - app-network
    command: npm run storybook -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  pkg_cache:
  db_data:
